package:
  name: climlab
  version: '0.4.3.dev0'

source:
  git_rev: v0.4.3.dev0
  git_url: https://github.com/brian-rose/climlab.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - netcdf4
    - pytest

  run:
    - python

test:
  imports:
    - climlab

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_file: LICENSE
