package:
  name: climlab
  version: '0.5.1dev0'

source:
  git_url: https://github.com/brian-rose/climlab.git
  git_tag: devel

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pytest

  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - pytest

test:
  imports:
    - climlab

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_file: LICENSE
