{% set name = "climlab" %}
{% set version = "0.6.0.dev6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  #skip: True  # [not py2k]

requirements:
  build:
    - toolchain
    - mingwpy  # [win]
    - gcc  # [osx]
    - python
    - setuptools
    - libgfortran  # [linux]
    - numpy x.x

  run:
    - python
    - numpy x.x
    - scipy
    - netcdf4
    - pytest
    - libgfortran  # [linux or osx]
    - future
    - numba

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v --pyargs climlab.tests

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
