name: climlab
dependencies:
    - python=2.7
    - numpy
    - scipy
    - netCDF4
    - sphinx
    - matplotlib
    - ipython
    - jupyter
    - pip:
        - nbsphinx
        - sphinxcontrib-bibtex
        - numpydoc
