name: climlab
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.5
    - numpy
    - scipy
    - netCDF4
    - sphinx
    - matplotlib
    - ipython
    - jupyter
    - sphinx_rtd_theme
    - nbsphinx
    - sphinxcontrib-bibtex
    - numpydoc
